labels:
  - id: 0
    color: [0,0,0]
    name: 'background'
  - id: 1
    color: [255, 0, 0]
    name: 'hand'
  - id: 2
    color: [0, 0, 255]
    name: 'body'

trainspec:
  dbroot: 'data/db'
  downsample: 1
  balance: 'True'
  discard: 'None'

model: [RandomForestClassifier, {'min_samples_split': 1, 'n_estimators': 20}]

features:
  blocksize: 8
  skip: 2
  kind: [['Hist', {'nbins': 16}]]
